// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tools-back/ent/predicate"
	"tools-back/ent/review"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ru *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUserUUID sets the "user_uuid" field.
func (ru *ReviewUpdate) SetUserUUID(u uuid.UUID) *ReviewUpdate {
	ru.mutation.SetUserUUID(u)
	return ru
}

// SetNillableUserUUID sets the "user_uuid" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableUserUUID(u *uuid.UUID) *ReviewUpdate {
	if u != nil {
		ru.SetUserUUID(*u)
	}
	return ru
}

// SetToolUUID sets the "tool_uuid" field.
func (ru *ReviewUpdate) SetToolUUID(u uuid.UUID) *ReviewUpdate {
	ru.mutation.SetToolUUID(u)
	return ru
}

// SetNillableToolUUID sets the "tool_uuid" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableToolUUID(u *uuid.UUID) *ReviewUpdate {
	if u != nil {
		ru.SetToolUUID(*u)
	}
	return ru
}

// SetRating sets the "rating" field.
func (ru *ReviewUpdate) SetRating(i int) *ReviewUpdate {
	ru.mutation.ResetRating()
	ru.mutation.SetRating(i)
	return ru
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableRating(i *int) *ReviewUpdate {
	if i != nil {
		ru.SetRating(*i)
	}
	return ru
}

// AddRating adds i to the "rating" field.
func (ru *ReviewUpdate) AddRating(i int) *ReviewUpdate {
	ru.mutation.AddRating(i)
	return ru
}

// SetComment sets the "comment" field.
func (ru *ReviewUpdate) SetComment(s string) *ReviewUpdate {
	ru.mutation.SetComment(s)
	return ru
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableComment(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetComment(*s)
	}
	return ru
}

// SetCreatedAt sets the "created_at" field.
func (ru *ReviewUpdate) SetCreatedAt(t time.Time) *ReviewUpdate {
	ru.mutation.SetCreatedAt(t)
	return ru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableCreatedAt(t *time.Time) *ReviewUpdate {
	if t != nil {
		ru.SetCreatedAt(*t)
	}
	return ru
}

// Mutation returns the ReviewMutation object of the builder.
func (ru *ReviewUpdate) Mutation() *ReviewMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReviewUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *ReviewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.UserUUID(); ok {
		_spec.SetField(review.FieldUserUUID, field.TypeUUID, value)
	}
	if value, ok := ru.mutation.ToolUUID(); ok {
		_spec.SetField(review.FieldToolUUID, field.TypeUUID, value)
	}
	if value, ok := ru.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ru.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if value, ok := ru.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetUserUUID sets the "user_uuid" field.
func (ruo *ReviewUpdateOne) SetUserUUID(u uuid.UUID) *ReviewUpdateOne {
	ruo.mutation.SetUserUUID(u)
	return ruo
}

// SetNillableUserUUID sets the "user_uuid" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableUserUUID(u *uuid.UUID) *ReviewUpdateOne {
	if u != nil {
		ruo.SetUserUUID(*u)
	}
	return ruo
}

// SetToolUUID sets the "tool_uuid" field.
func (ruo *ReviewUpdateOne) SetToolUUID(u uuid.UUID) *ReviewUpdateOne {
	ruo.mutation.SetToolUUID(u)
	return ruo
}

// SetNillableToolUUID sets the "tool_uuid" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableToolUUID(u *uuid.UUID) *ReviewUpdateOne {
	if u != nil {
		ruo.SetToolUUID(*u)
	}
	return ruo
}

// SetRating sets the "rating" field.
func (ruo *ReviewUpdateOne) SetRating(i int) *ReviewUpdateOne {
	ruo.mutation.ResetRating()
	ruo.mutation.SetRating(i)
	return ruo
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableRating(i *int) *ReviewUpdateOne {
	if i != nil {
		ruo.SetRating(*i)
	}
	return ruo
}

// AddRating adds i to the "rating" field.
func (ruo *ReviewUpdateOne) AddRating(i int) *ReviewUpdateOne {
	ruo.mutation.AddRating(i)
	return ruo
}

// SetComment sets the "comment" field.
func (ruo *ReviewUpdateOne) SetComment(s string) *ReviewUpdateOne {
	ruo.mutation.SetComment(s)
	return ruo
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableComment(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetComment(*s)
	}
	return ruo
}

// SetCreatedAt sets the "created_at" field.
func (ruo *ReviewUpdateOne) SetCreatedAt(t time.Time) *ReviewUpdateOne {
	ruo.mutation.SetCreatedAt(t)
	return ruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableCreatedAt(t *time.Time) *ReviewUpdateOne {
	if t != nil {
		ruo.SetCreatedAt(*t)
	}
	return ruo
}

// Mutation returns the ReviewMutation object of the builder.
func (ruo *ReviewUpdateOne) Mutation() *ReviewMutation {
	return ruo.mutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ruo *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Review entity.
func (ruo *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.UserUUID(); ok {
		_spec.SetField(review.FieldUserUUID, field.TypeUUID, value)
	}
	if value, ok := ruo.mutation.ToolUUID(); ok {
		_spec.SetField(review.FieldToolUUID, field.TypeUUID, value)
	}
	if value, ok := ruo.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if value, ok := ruo.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Review{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
